---
name: Hashicorp Vault Testing
on:
  pull_request:

jobs:
  test:
    name: Hashicorp Vault Testing
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Updating packages
        run: sudo apt update

      - name: Installing docker
        run: sudo apt install docker-ce docker-ce-cli -y

      - name: Installing python3
        run: -|
          sudo apt install python3 python3-pip -y;
          pip3 install numpy;
          pip3 install requests-ntlm;

      - name: Installing java and graphviz
        run: sudo apt install default-jre graphviz -y

      - name: Starting the hashicorp vault container
        run: |-
          cd ./.github/workflows/hashicorp_vault_testing/
          docker compose up --detach;
          cd $GITHUB_WORKSPACE;

      - name: Coffee Break ☕
        run: sleep 15

      - name: Starting test shell script
        run: |-
          python3 sscrawl.py --url "http://127.0.0.1:8200" --server 'hashicorp' --insecure --user 'aafab6b2-4de6-b72f-d8b2-e7c95d1d162a' --pwd '75091e8c-0c11-510e-b1e3-e87ddd50c27c' --recursive --graph --verbose

      - name: Output content to stdout
        run: |-
          echo '[+] Found Secrets';
          cat sscrawl_files/sscrawl_secrets.out;
          echo '[+] Graph PlantUML File';
          cat sscrawl_files/graph.plantuml

      - name: Generate the UML graph with PlantUML
        run: |-
          curl -L https://github.com/plantuml/plantuml/releases/download/v1.2023.12/plantuml.jar --output plantuml.jar;
          java -Djava.awt.headless=true -jar plantuml.jar sscrawl_files/graph.plantuml -svg

      - name: Upload graph image
        id: upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: graph.svg
          path: ./sscrawl_files/graph.svg
          if-no-files-found: error

  comment-image:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get Artifact URL & PR Info
        env:
          GITHUB_TOKEN: ${{ github.token }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          WORKFLOW_RUN_EVENT_OBJ: ${{ toJSON(github.event.workflow_run) }}
        run: |

          PREVIOUS_JOB_ID=$(jq -r '.id' <<< "$WORKFLOW_RUN_EVENT_OBJ")
          echo "Previous Job ID: $PREVIOUS_JOB_ID"
          echo "PREVIOUS_JOB_ID=$PREVIOUS_JOB_ID" >> "$GITHUB_ENV"

          ARTIFACT_URL=$(gh api "/repos/$OWNER/$REPO/actions/artifacts" \
            --jq ".artifacts.[] |
            select(.workflow_run.id==${PREVIOUS_JOB_ID}) |
            select(.expired==false) |
            .archive_download_url")

          echo "ARTIFACT URL: $ARTIFACT_URL"
          echo "ARTIFACT_URL=$ARTIFACT_URL" >> "$GITHUB_ENV"

          PR_NUMBER=$(jq -r '.pull_requests[0].number' \
            <<< "$WORKFLOW_RUN_EVENT_OBJ")

          echo "PR Number: $PR_NUMBER"
          echo "PR_NUMBER=$PR_NUMBER" >> "$GITHUB_ENV"

          HEAD_SHA=$(jq -r '.pull_requests[0].head.sha' \
            <<< "$WORKFLOW_RUN_EVENT_OBJ")

          echo "Head sha: $HEAD_SHA"
          echo "HEAD_SHA=$HEAD_SHA" >> "$GITHUB_ENV"

      - name: Update Comment
        env:
          JOB_PATH: "${{ github.server_url }}/${{ github.repository }}/actions/\
            runs/${{ env.PREVIOUS_JOB_ID }}"
          HEAD_SHA: ${{ env.HEAD_SHA }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ env.PR_NUMBER }}
          body: |-
            ![badge]

            Build Successful! Here is the generated graph:

            ![HashiCorp Vault Graph](${{ env.ARTIFACT_URL }})

            ---

            | Name     | Link                    |
            | -------- | ----------------------- |
            | Commit   | ${{ env.HEAD_SHA }}     |
            | Logs     | ${{ env.JOB_PATH }}     |
            | Download | ${{ env.ARTIFACT_URL }} |

            [badge]: https://img.shields.io/badge/Build_Success!-0d1117?style=for-the-badge&labelColor=3fb950&logo=data:image/svg%2bxml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgd2lkdGg9IjI0IiBoZWlnaHQ9IjI0IiBmaWxsPSIjZmZmZmZmIj48cGF0aCBkPSJNMjEuMDMgNS43MmEuNzUuNzUgMCAwIDEgMCAxLjA2bC0xMS41IDExLjVhLjc0Ny43NDcgMCAwIDEtMS4wNzItLjAxMmwtNS41LTUuNzVhLjc1Ljc1IDAgMSAxIDEuMDg0LTEuMDM2bDQuOTcgNS4xOTVMMTkuOTcgNS43MmEuNzUuNzUgMCAwIDEgMS4wNiAwWiI+PC9wYXRoPjwvc3ZnPg==
